### ISSUE TITLE
SI B2 Model06 Simulation 

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-dipoles-b2#1]
si-dipoles-b2/model-06/simulation/magnetic/2017-01-19_B2_Model06_Sim_X=-63_27mm_Z=-1000_1000mm_Imc=452.4A.txt

**Comment by xresende** [comment]
fmap analyzed. beam dynamics calculation with multipolos of b1 and b2 being run...

**Comment by LuanaVilela** [comment]
Added new model fieldmap (Model 07):

 si-dipoles-b2/model-07/simulation/magnetic/2017-02-01_B2_Model07_Sim_X=-63_27mm_Z=-1000_1000mm_Imc=451.8A.txt
