### ISSUE TITLE
B2 Model08 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-dipoles-b2#3]
Added new model for analysis (model approved by the LNLS PRO group):

 si-dipoles-b2/model-08/simulation/magnetic/2017-05-17_B2_Model08_Sim_X=-63_27mm_Z=-1000_1000mm_Imc=394.1A.txt

**Comment by xresende** [comment]
- fieldmap analysed. specs (deflection, integrated quad) achieved.
- beam dynamical aperture calculations running.
- wiki updated

**Comment by xresende** [comment]
- calculations show no DA reduction as compared to previous official models.
- AT model needs resymmetrisation.

**Comment by xresende** [comment]
Resymmetrisation of AT model for SI was done.
